server:
  port: 8001


#security:
#  basic:
#    enabled: true # 启用SpringSecurity的安全配置项
#  user:
#    name: liuliang  # 认证用户名
#    password: hello #认证密码
#    role:           #授权角色
#    - USER
#  sessions: stateless #标准做法：session设为不保存session状态，否则会导致rest服务内存被session状态占满（因为访问用户很大) always表示保存

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.ll.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
    - classpath:mybatis/mapper/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/microcloud8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: liuliang125                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间